# Generated by Django 4.2.4 on 2024-09-11 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_by_id', models.IntegerField()),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('news_content_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('view_data', models.JSONField(null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by_id', models.IntegerField()),
                ('updated_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated_by_id', models.IntegerField()),
            ],
            options={
                'db_table': 'news_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsContentAssets',
            fields=[
                ('news_content_asset_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news_content_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='SourceAttributes',
            fields=[
                ('source_attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.source')),
            ],
            options={
                'db_table': 'source_attributes',
            },
        ),
    ]
