# Generated by Django 4.2.4 on 2024-09-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceattributes',
            name='value',
            field=models.TextField(),
        ),
    ]
